apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "fullname" . }}
    helm.sh/chart: {{ include "chart" . }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fullname" . }}
      # app.kubernetes.io/instance: {{ .Release.Name }}
      # app.kubernetes.io/name: {{ include "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ include "fullname" . }}
        version: stable
{{- with .Values.pod.labels }}
{{ toYaml . | indent 8 }}
{{- end }}
      annotations:
        buildID: {{ .Values.buildID }}
{{- with .Values.pod.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
{{ if .Values.hostNetwork }}
        hostNetwork: {{ .Values.hostNetwork }}
{{ end }}
{{ if .Values.dnsPolicy }}
        dnsPolicy: {{ .Values.dnsPolicy }}
{{ end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        env:
          - name: PROFILE
            value: {{ .Values.profile }}
          - name: NAMESPACE
            value: {{ .Values.namespace }}
{{ if or .Values.configmap.enabled .Values.secret.enabled }}
        envFrom:
{{ end }}
{{ if .Values.configmap.enabled }}
          - configMapRef:
              name: {{ include "fullname" . }}
{{ end }}
{{ if .Values.secret.enabled }}
          - secretRef:
              name: {{ include "fullname" . }}
{{ end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
{{- end }}
