apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
          - name: PROFILE
            value: {{ .Values.profile }}
{{ if or .Values.configmap.enabled .Values.secret.enabled }}
        envFrom:
{{ end }}
{{ if .Values.configmap.enabled }}
          - configMapRef:
              name: {{ template "fullname" . }}
{{ end }}
{{ if .Values.secret.enabled }}
          - secretRef:
              name: {{ template "fullname" . }}
{{ end }}
