{{ if .Values.ingress.enabled }}
{{- $fullName := include "fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "fullname" . }}
    helm.sh/chart: {{ include "chart" . }}
{{- with .Values.ingress.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
{{ if and .Values.ingress.subdomain .Values.ingress.basedomain }}
  - host: {{ .Values.ingress.subdomain }}.{{ .Values.ingress.basedomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $servicePort }}
{{ end }}
{{ range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $servicePort }}
{{ end }}
{{ end }}
