{{ if .Values.pdb }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
spec:
{{ toYaml .Values.pdb | indent 2 }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
{{ end }}
