apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "fullname" . }}
    helm.sh/chart: {{ include "chart" . }}
{{- with .Values.service.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if (and (eq .Values.service.type "ClusterIP") (not (empty .Values.service.clusterIP))) }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
  ports:
  - name: http
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
{{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ include "fullname" . }}
    # app.kubernetes.io/instance: {{ .Release.Name }}
    # app.kubernetes.io/name: {{ include "fullname" . }}
