# gitlab-ci

image: docker:stable

services:
  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

stages:
  - build
  - release

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -f Dockerfile-alpine -t $IMAGE_TAG .

release:
  stage: release
  script:
    - docker push $IMAGE_TAG
