# Dockerfile

FROM maven as BUILD
COPY . /data/src/
RUN mvn -f /data/src/pom.xml clean package -DskipTests

FROM tomcat:8-jre8-alpine
RUN apk add --no-cache bash curl
RUN rm -rf /usr/local/tomcat/webapps/*
EXPOSE 8080
COPY --from=BUILD /data/src/target/*.war /usr/local/tomcat/webapps/ROOT.war
