# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: sample-tomcat
replicaCount: 2
image:
  repository: docker-registory/sample-tomcat
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: java
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi
ingress:
  enabled: true
basedomain: apps.opspresso.com
