replicaCount: 1
image:
  repository: docker-registry.127.0.0.1.nip.io:30500/sample-tomcat
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi
ingress:
  enabled: true
  basedomain: 127.0.0.1.nip.io
hpa:
  enabled: true
  min: 1
  max: 5
  cpu: 50
profile: default
configmap:
  enabled: false
secret:
  enabled: false
