replicaCount: 1
image:
  repository: acme
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi
ingress:
  enabled: true
  basedomain: opspresso.com
hpa:
  enabled: true
  min: 1
  max: 5
  cpu: 50
env:
  # - name: GREETING
  #   value: "Hello from the environment"
envFrom:
  # - configMapRef:
  #   name: sample-config-map
configmap:
  enabled: false
secret:
  enabled: false
