name: Build-Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Bump Version
        uses: opspresso/action-builder@v0.2.5
        with:
          args: --version

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          node-version: "12.x"

      - name: Run Build
        run: |
          ./build.sh

      - name: Release to GitHub
        uses: opspresso/action-builder@v0.2.5
        with:
          args: --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Trigger for GitOps
      #   uses: opspresso/action-builder@v0.2.5
      #   with:
      #     args: --dispatch
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GITOPS_REPO: "nalbam/argocd-env-demo"
      #     EVENT_TYPE: "build"
      #     TARGET_ID: "deepracer-timer"

      # - name: Build & Push to Docker Hub
      #   uses: opspresso/action-builder@v0.2.5
      #   with:
      #     args: --docker
      #   env:
      #     # USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     LATEST: "true"

      - name: Build & Push to GitHub Package
        uses: opspresso/action-builder@v0.2.5
        with:
          args: --docker
        env:
          # USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
          REGISTRY: "docker.pkg.github.com"
          LATEST: "true"

      - name: Build & Push to AWS ECR
        uses: opspresso/action-builder@v0.2.5
        with:
          args: --ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
          LATEST: "true"
